version: "3.9"
services:
    db:
        container_name: mysql
        image: mysql:latest
        command: "--default-authentication-plugin=mysql_native_password"
        volumes:
            - data:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mysql_root_password
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        expose:
            - 3306
            - 33060

    wordpress:
        container_name: wordpress
        image: wordpress:latest
        depends_on:
            - db
        ports:
            - 8000:80
        restart: always
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpress
        volumes:
            - ./app/:/var/www/html/
        extra_hosts:
            - "host.docker.internal:host-gateway"

    adminer:
        container_name: adminer
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db

volumes:
    data:
